# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name: 'Default'
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# 1Setup .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0.x'

# Restore NuGet packages
- script: dotnet restore
  displayName: 'Restore NuGet packages'

# Build project
- script: dotnet build --configuration Release
  displayName: 'Build project'

# Run tests
- script: dotnet test --no-build --verbosity normal
  displayName: 'Run tests'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'


